version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.0
    container_name: airflow-init
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-db/airflow
      PYTHONPATH: /opt/airflow

    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - airflow

  airflow-webserver:
    image: apache/airflow:2.8.0
    container_name: airflow-server
    user: "root"
    command: webserver
    ports:
      - "8070:8080"
    environment:
      - PYTHONPATH: /opt/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/gcp/gcp-credentials.json
      - AIRFLOW__CORE__EXECUTOR: LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-db/airflow
      - AIRFLOW__CORE__FERNET_KEY: ''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      - AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      

    volumes:
      - ./data:/opt/airflow/data
      - ./gcp:/opt/airflow/gcp
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres-db:
        condition: service_healthy
    networks:
      - airflow

  airflow-scheduler:
    
    image: apache/airflow:2.8.0
    container_name: airflow-scheduler
    command: scheduler
    environment:
      - PYTHONPATH: /opt/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/gcp/gcp-credentials.json
      - AIRFLOW__CORE__EXECUTOR: LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-db/airflow
      - PYTHONPATH: /opt/airflow

    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./gcp:/opt/airflow/gcp
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres-db:
        condition: service_healthy
    networks:
      - airflow

  python-custom:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-project:latest
    container_name: python-custom
    command: ["tail", "-f", "/dev/null"]
    restart: "no"
    networks:
      - airflow

networks:
  airflow:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  airflow-data:
    driver: local
